# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fray < Formula
  desc "Agent-first, non-custodial betting CLI for Fray"
  homepage "https://fray.bet"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fraybet/cli/releases/download/v0.1.0/fray_0.1.0_darwin_amd64.tar.gz"
      sha256 "b09ab40b681325bf2f985c9aba47bbead3581245751ead5cf3feef9bb6aec3c0"

      define_method(:install) do
        bin.install "fray"
        bin.install "fray-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fraybet/cli/releases/download/v0.1.0/fray_0.1.0_darwin_arm64.tar.gz"
      sha256 "28b21711058473afe1c675d6d4c610b5ef49069545f6dd8c152083bbd0500d5a"

      define_method(:install) do
        bin.install "fray"
        bin.install "fray-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fraybet/cli/releases/download/v0.1.0/fray_0.1.0_linux_amd64.tar.gz"
      sha256 "39f4735501c210082742d161b3d67b8c1a827eb19a34671a1ee8b70457a109d2"
      define_method(:install) do
        bin.install "fray"
        bin.install "fray-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fraybet/cli/releases/download/v0.1.0/fray_0.1.0_linux_arm64.tar.gz"
      sha256 "fa3364c11ccc9792bd83672122c3c6abfe6cb4ac9a189664ee20f46e77377776"
      define_method(:install) do
        bin.install "fray"
        bin.install "fray-mcp"
      end
    end
  end

  test do
    system "#{bin}/fray", "version"
  end
end
